{{- range $ncName, $ncData := .Values.nodeClasses }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $ncName | quote }}
spec:
  {{- with $ncData.amiFamily }}
  amiFamily: {{ . | default "AL2" }}
  {{- end }}
  {{- with required "subnetSelectorTerms is required" $ncData.subnetSelectorTerms }}
  subnetSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with required "securityGroupSelectorTerms is required" $ncData.securityGroupSelectorTerms }}
  securityGroupSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ncData.role }}
  role: {{ . }}
  {{- end }}
  {{- with $ncData.instanceProfile }}
  instanceProfile: {{ . }}
  {{- end }}
  {{- with $ncData.amiSelectorTerms }}
  amiSelectorTerms:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ncData.tags }}
  tags:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with $ncData.metadataOptions }}
  metadataOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $ncData.instanceStorePolicy }}
  instanceStorePolicy: {{ . }}
  {{- end }}
  {{- with $ncData.userData }}
  userData: {{ . }}
  {{- end }}
  {{- with $ncData.detailedMonitoring }}
  detailedMonitoring: {{ . }}
  {{- end }}
  {{- with $ncData.associatePublicIPAddress }}
  associatePublicIPAddress: {{ . }}
  {{- end }}
{{- end }}